### ISSUE TITLE
emacs-workspaces--project-name potential problems

### ISSUE THREAD

**Issue by mfiano** [mclear-tools/emacs-workspaces#3]
Forgive me, as I'm not an Emacs Lisp coder (Common Lisp actually), but I find some things possibly wrong with the `cond` form [here](https://github.com/mclear-tools/emacs-workspaces/blob/main/emacs-workspaces.el#L137-L143)

- `(vc-root-dir)` could be lexically bound as to not call it twice.
- the `vc-call-backend` branch seems to not have a value and is returning `nil`?
- The catch-all `t` branch is returning the same string as the previous branch, making the previous branch un-necessary?

**Comment by mclearc** [comment]
Thanks! -- I'm not really an elisp coder either (not a coder at all, actually :)) So there is a lot of potential here for the code to be fragile. I'll take a look at these soon.

**Comment by mclearc** [comment]
Closed by https://github.com/mclear-tools/emacs-workspaces/commit/e19d9225e04c02897aac95b25fbfcfd6f0029139
