### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by bbenne10** [mclear-tools/emacs-workspaces#4]
Hello. I'm very interested in this project as the goals line up well with my own attempts to minimize large external projects and make better use of emacs  built-in functionality.

I just forked the repository to add a [nix flake ](https://nixos.wiki/wiki/Flakes) for my own consumption (since this is not present in MELPA). When writing the flake, I realized that I had no idea what the license for this project is, which leaves me in a bit of a pickle as, while I believe you intend for this to be available for public consumption and modification, [not choosing a license means you have withheld exclusive copyright](https://choosealicense.com/no-permission/). 

Picking a license is your decision as the maintainer. I do not have much of an opinion but, emacs being a GNU project, the obvious choice is the GPLv3. I would suggest having a read over [https://choosealicense.com ](https://choosealicense.com)and picking one. There are a number of available options, but this site does a great job of presenting the options in a concise and clear manner.

**Comment by mclearc** [comment]
Thanks -- I had the MIT license in the boilerplate at the top of the .el file but I see that I need to have a separate LICENSE file for MELPA. Easy enough.

**Comment by mclearc** [comment]
Closed by c91858b4b5337459e60132549296acb0e3fce53c
