### ISSUE TITLE
Submit to MELPA

### ISSUE THREAD

**Issue by bbenne10** [mclear-tools/emacs-workspaces#5]
Once #4 is resolved, I believe that this project would see a lot more usage if it were submitted to melpa (rather than requiring straight or manual cloning). I have not yet looked deeply into how to achieve this, but I do know that there will need to be a recipe created and a maintainer for that recipe selected. MELPA's repo suggests that the emacs package author take over the MELPA recipe author role for their particular packages. 

If there's anything I can do to help in this effort, please don't hesitate to ask. Thank you.

**Comment by mclearc** [comment]
Thanks for the encouragement -- I'd been waiting to see how stable the code was and whether anyone turned up any obvious bugs. But it seems like it's fairly stable now and so I'll look into putting it on MELPA this weekend.

**Comment by mclearc** [comment]
Closed via https://github.com/melpa/melpa/pull/7970

**Comment by bbenne10** [comment]
I don't want to jump into the melpa PR and noisy that whole thing up (it seems busy enough as is!), but for "not a software developer", you've been an amazing responsive and helpful software developer and maintainer. Thank you for moving quickly on this!

**Comment by mclearc** [comment]
`tabspaces` has been merged to melpa -- thanks again for your encouragement!
